# Generated by Django 3.1.7 on 2021-04-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210411_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=50)),
                ('post', models.TextField(blank=True, max_length=200)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='home/images')),
            ],
        ),
    ]
