# Generated by Django 3.1.7 on 2021-04-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cropguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropguide',
            name='post',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
