# Generated by Django 3.1.7 on 2021-05-01 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210501_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
    ]
