# Generated by Django 3.1.7 on 2021-05-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropguide',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
