# Generated by Django 3.1.7 on 2021-05-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210521_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='username',
        ),
    ]
