# Generated by Django 3.1.7 on 2021-05-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20210522_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='d_status',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
