# Generated by Django 3.1.7 on 2021-05-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_purchase_d_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='p_status',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
