# Generated by Django 3.1.7 on 2021-05-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20210523_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='field_name',
        ),
        migrations.AddField(
            model_name='crop',
            name='unit2',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
